@BASE_URL=http://localhost:3001

GET {{BASE_URL}}

###

GET {{BASE_URL}}/api/contacts

###

GET {{BASE_URL}}/api/contacts/f0db021e-2bcd-47dd-8ca0-f064803421c2

###

POST {{BASE_URL}}/api/contacts
Content-Type: application/json

{
    "name": "Ajay Kumar",
    "email": "ajay@gmail.com",
    "phone": "8218150662",
    "type": "PROFESSIONAL"
}

###

PUT {{BASE_URL}}/api/contacts/apnaID
Content-Type: application/json

{
    "name": "Ankit",
    "age": 32
}

###

GET {{BASE_URL}}/try/abhay

###

DELETE {{BASE_URL}}/api/contacts/545310dc-58f2-442d-98e8-9eeecf5fa980
